
development:
  adapter: postgresql
  encoding: unicode
  database: zype_test_video_development
  pool: 5
  username: AdiSingh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: zype_test_video_test
  pool: 5
  username: AdiSingh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: zype_test_video_production
  pool: 5
  username: AdiSingh
  password:
